### PR TITLE
Enhanced properties retrieval

### PR DESCRIPTION
**Pull request by krichter722**
Based on the current undocumented (and for me personally hard to get) retrieval of properties (see #162) the mechanism has been rewritten drastically. The changes include:

  * hiding of URLs. Guice and other properties consumers want `Properties`, so method should return such.
  * `.properties` files shouldn't be searched in the current directory or in the source root. Therefore default properties are now maintained in an application resource and can be overwritten by both files and resources on classpath if the corresponding system property is set (see Javadoc of OrienteerModule). There's a fallback so that Properties are always retrieved. A `.properties` file can be put in `~/.orienteer/orienteer.properties` and is used if no system property is specified.
  * The default properties are maintained in the newly created project `orienteer-resources`.

A test for `OrienteerModule` has been created. The `orienteer-archetype-war` project has been adjusted to match the changes listed above.

The reason for the change was that I could never build Orienteer due to issue in intransparent properties loading.

### CODE REVIEW

**Comment by PhantomYdn** [comment]
Thank you! But lets discuss: I see few things that contradict with my understanding how it should be organized. 

0) I do agree that passing of Properties instead of URL is better.
1) Could you please describe what was your initial problem? What kind of symptoms did you have?
2) The idea of "default properties" has been used for the following feature: there is standalone Orienteer (single jar with all dependencies) and I thought that it will be cool if by just double click you can run Orienteer. So no writing properties, no application servers: just single file - run it and Orienteer is running.
3) From my point of view: orienteer.properties is not an resources. That's configration: so might be seprate config directory will be good, but I don't see any reason to have dedicated maven module.

So: I agree that changes required, but I think that a) no additional module for that stuff required b) lookup of file by scanning up is good(at least I've already use that my zoo of Orienteer's:) ).

**Comment by PhantomYdn** [comment]
Btw, I updated wiki https://github.com/PhantomYdn/Orienteer/wiki/How-to-run-Orienteer to reflected currently existing ways to start Orienteer.

**Comment by krichter722** [comment]
>  1) Could you please describe what was your initial problem? What kind of symptoms did you have?

Properties were not found and Guice failed to initialize (I guess the exact exception doesn't matter because it was definitely due to missing properties).

>  2) The idea of "default properties" has been used for the following feature: there is standalone Orienteer (single jar with all dependencies) and I thought that it will be cool if by just double click you can run Orienteer. So no writing properties, no application servers: just single file - run it and Orienteer is running.

But that's the case now (in my changes Properties are always returned), not before (where there must have been a case where `null` as Properties (or URL in that case) was returned).

> 3) From my point of view: orienteer.properties is not an resources. That's configration: so might be seprate config directory will be good, but I don't see any reason to have dedicated maven module.

Some folks might want to specify configuration packaged with their modules on the classpath and don't bother with local file system access. It's no obligatory in my changes (you can specify a config file, a resource on classpath, put a file in `~/.orienteer/orienteer.properties` or nothing of that and let properties fallback to built-in defaults.

I don't care where we put the default properties (own module, in `orienteer-core` or hard code it into the source), adding a separate module to the war would be no problem, though and one-file war deployment would still be guaranteed (that's the purpose of a war file and it'd take a lot more to break that concept ;)).

**Comment by PhantomYdn** [comment]
I see what are you saying... If you don't mind I will slightly modify your realization in a separate branch and then commit into master. I need to support my current infrastructure of Orienteer:)

**Comment by krichter722** [comment]
Of course, it was an undiscussed change, take what you can use and modify at will :) I'll see if properties are still missing at start of Orienteer/initialization of guice and open an issue if issues persist.

**Comment by krichter722** [comment]
The issue didn't occur during build, but during deployment on Glassfish 4.1. I'm getting the error

    Information:   ERROR - WicketFilter               - The initialization of an application with name 'wicket.orienteer' has failed.
    com.google.inject.CreationException: Guice creation errors:
    1) Properties files was not found
    2) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getLocalizer(OrienteerModule.java:120)
    3) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getOServer(OrienteerModule.java:113)
    3 errors
	    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	    at com.google.inject.Guice.createInjector(Guice.java:95)
	    at com.google.inject.Guice.createInjector(Guice.java:72)
	    at com.google.inject.Guice.createInjector(Guice.java:62)
	    at org.apache.wicket.guice.GuiceWebApplicationFactory.createApplication(GuiceWebApplicationFactory.java:171)
	    at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:385)
	    at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:351)
	    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:275)
	    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:131)
	    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:5329)
	    at org.apache.catalina.core.StandardContext.start(StandardContext.java:5943)
	    at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
	    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
	    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
	    at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	    at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	    at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	    at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	    at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at javax.security.auth.Subject.doAs(Subject.java:360)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at javax.security.auth.Subject.doAs(Subject.java:360)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	    at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	    at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	    at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	    at java.lang.Thread.run(Thread.java:745)
    Schwerwiegend:   WebModule[/orienteer-war]Exception starting filter wicket.orienteer
    java.lang.InstantiationException
	    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:135)
	    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:5329)
	    at org.apache.catalina.core.StandardContext.start(StandardContext.java:5943)
	    at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
	    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
	    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
	    at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	    at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	    at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	    at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	    at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at javax.security.auth.Subject.doAs(Subject.java:360)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at javax.security.auth.Subject.doAs(Subject.java:360)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	    at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	    at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	    at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.servlet.ServletException: com.google.inject.CreationException: Guice creation errors:
    1) Properties files was not found
    2) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getLocalizer(OrienteerModule.java:120)
    3) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getOServer(OrienteerModule.java:113)
    3 errors
	    at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:450)
	    at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:351)
	    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:275)
	    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:131)
	    ... 51 more
    Caused by: com.google.inject.CreationException: Guice creation errors:
    1) Properties files was not found
    2) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getLocalizer(OrienteerModule.java:120)
    3) No implementation for org.apache.wicket.protocol.http.WebApplication was bound.
      at org.orienteer.services.OrienteerModule.getOServer(OrienteerModule.java:113)
    3 errors
	    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	    at com.google.inject.Guice.createInjector(Guice.java:95)
	    at com.google.inject.Guice.createInjector(Guice.java:72)
	    at com.google.inject.Guice.createInjector(Guice.java:62)
	    at org.apache.wicket.guice.GuiceWebApplicationFactory.createApplication(GuiceWebApplicationFactory.java:171)
	    at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:385)
	    ... 54 more

during start of the application on the server. I'm using the default "Debug" command after opening the project in NetBeans 8.0.2 (I can research the exact command set if necessary).

**Comment by PhantomYdn** [comment]
I'm working right now on that:) A couple of minutes and I will commit update.

**Comment by PhantomYdn** [comment]
Commited! Please check updated version.

**Pull request closed without merging**
